{
 "title": "Boavizta-cloud-scan-account",
 "description": "Environmental impacts of aws EC2 instances of account",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region" }
  ]
 },
 "panels": [
  {
   "title": "Number of instances assessed",
   "type": "stat",
   "description": "Number of instances really taken into account for impact calculations (some instance types have no data in Boavizta dataset).",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boavizta_number_of_instances_assessed",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  },
  {
   "title": "Number of instances total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boavizta_number_of_instances_total",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  },
  {
   "title": "Number of instances (taken into assessment)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "boavizta_number_of_instances_assessed",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  },
  {
   "title": "Regional GWP (Manuf) / Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kgco2eq" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boavizta_gwp_manufacture_kgco2eq",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  },
  {
   "title": "Regional GWP (Use) / Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kgco2eq" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "boavizta_gwp_use_kgco2eq", "legendFormat": "{{country}} ({{awsregion}})" }
   ]
  },
  {
   "title": "Primary Energy Factor (use) MJ/kWh",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "MJ" } },
   "targets": [
    { "expr": "boavizta_pe_use_megajoules", "legendFormat": "{{country}} ({{awsregion}})" }
   ]
  },
  {
   "title": "adp manuf",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kgsbeq" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boavizta_adp_manufacture_kgsbeq",
     "legendFormat": "{{awsregion}}"
    }
   ]
  },
  {
   "title": "adp use",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kgsbeq" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "boavizta_adp_use_kgsbeq", "legendFormat": "{{awsregion}}" }
   ]
  },
  {
   "title": "Global Warming Potential (of use) in kgco2eq",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "MJ" } },
   "targets": [
    { "expr": "boavizta_gwp_use_kgco2eq", "legendFormat": "{{country}} ({{awsregion}})" }
   ]
  },
  {
   "title": "Regional Pe (Manuf)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MJ" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boavizta_pe_manufacture_megajoules",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  },
  {
   "title": "Regional Pe (Use) / Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MJ" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "boavizta_pe_use_megajoules", "legendFormat": "{{country}} ({{awsregion}})" }
   ]
  },
  {
   "title": "Abiotic Resource Depletion (Manufacture) kgsbeq",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kgsbeq" } },
   "targets": [
    {
     "expr": "boavizta_adp_manufacture_kgsbeq",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  }
 ]
}